Assistant/sara_fe/refactor
FEUP-MEIC-DS-2024-25/ai4sd pull request #132
Opened 2024-12-05 09:04 UTC by hfuturo

2024-12-06 23:14 UTC, MRita443 requested changes
Looks great, just some HTML guidelines my IDE nagged me about

2024-12-06 23:14 UTC, MRita443 commented on x-men/frontend/public/template/menu.html
> +                            <ul>
<p> element is not permitted as content under <span>html-validate(element-permitted-content)
<ul> element is not permitted as content under <span>html-validate(element-permitted-content)

Maybe change span to div?

2024-12-06 23:14 UTC, MRita443 commented on x-men/frontend/public/template/menu.html
> +                        <option value="local" selected="selected">Local</option>
Attribute "selected" should omit valuehtml-validate(attribute-boolean-style)
```suggestion
                        <option value="local" selected>Local</option>
```

2024-12-06 23:14 UTC, MRita443 commented on x-men/frontend/public/template/menu.html
>      </div>
You're missing a closing tag for a <div>

2024-12-06 23:14 UTC, MRita443 commented on x-men/frontend/public/template/menu.html
> +        <button id="submit">Submit</button>
<button> is missing recommended "type" attributehtml-validate(no-implicit-button-type)
```suggestion
        <button id="submit" type="submit">Submit</button>
```

2024-12-07 15:29 UTC, MRita443 approved these changes
LGTM :)

2024-12-07 17:50 UTC, IgorAndrade10 approved these changes

2024-12-07 17:50 UTC, IgorAndrade10 reviewed
Looks good

2024-12-07 17:55 UTC, merged